version: "3"

volumes:
  postgresql-volume:  # pointing volume to db

services:
  djangoapp:
    depends_on:
      - db
    build: ./fuzzysystem
    volumes:
      - ./fuzzysystem:/  # djangoapp mounted to docker from current directory
      - ./fuzzysystem/static:/static # adding static & media file for django
      - ./fuzzysystem/media:/media
    command: ./fuzzysystem/entrypoint.sh # execute bashfile we've created before

  db:
    image: postgres:alpine  # install postgre here
    volumes:
      - postgresql-volume:/var/lib/postgresql/data # avoid data removal when shut docker down we put volume in our local
